vich_uploader:
    db_driver: orm
    
    mappings:
        recette_image:
            uri_prefix: /images/recettes
            upload_destination: '%kernel.project_dir%/public/assets/recettes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        image_marque:
            uri_prefix: /images/marques
            upload_destination: '%kernel.project_dir%/public/assets/marques'
            namer: Vich\UploaderBundle\Naming\UniqidNamer