home:
  path : /
  controller: App\Controller\HomeController::index

recettes:
  path: /recettes
  controller: App\Controller\RecettesController::recettes

bonsplans:
  path: /bonsplans
  controller: App\Controller\BonsPlansController::bonsplans

contact:
  path: /contact
  controller: App\Controller\ContactController::contact



