home:
  path : /
  controller: App\Controller\HomeController::index

recettes:
  path: /recettes
  controller: App\Controller\RecettesController::recettes

bonsplans:
  path: /bonsplans
  controller: App\Controller\BonsPlansController::bonsplans

contact:
  path: /contact
  controller: App\Controller\ContactController::contact

show:
  path: /show/{id}
  controller:  App\Controller\RecettesController::show

admin:
  path: /admin
  controller:  App\Controller\Admin\AdminController::admin

edit:
  path: /edit/{id}
  controller:  App\Controller\Admin\AdminController::edit

logout: 
  path: /logout 

login:
  path: /login
  controller: App\Controller\SecurityController::login






